### ISSUE TITLE
Need rework for iOS 9

### ISSUE THREAD

**Issue by hfu** [gsi-cyberjapan/cmp#4]
It seems that the range bar at the bottom does not work properly on iOS 9.

Safari opens something like a zoomed area like the following:
![img_8968](https://cloud.githubusercontent.com/assets/18297/10194909/150df410-67c6-11e5-9c44-82f035847b1a.jpg)

The range bar does not work with Chrome. Sometimes Chrome opens a menu like the following:
![img_8969](https://cloud.githubusercontent.com/assets/18297/10194934/3f1296d0-67c6-11e5-826f-7bd6d3a3400f.jpg)

**Comment by frogcat** [comment]
http://touchpunch.furf.com/ says:

> Currently, jQuery UI user interface library does not support the use of touch events in their widgets and interactions.

So I forked and added jQuery UI Touch Punch library.
Please try this one.
- [joso.html](http://frogcat.github.io/cmp-1/?rl=ort&ll=20150911dol2&ovl=experimental_anno&lng=139.96672&lat=36.09894&z=16&lattr=%E5%B8%B8%E7%B7%8F%E5%9C%B0%E5%8C%BA%EF%BC%882015%E5%B9%B49%E6%9C%8811%E6%97%A5%E5%8D%88%E5%BE%8C%E6%92%AE%E5%BD%B1%29&rattr=%E9%9B%BB%E5%AD%90%E5%9B%BD%E5%9C%9F%E5%9F%BA%E6%9C%AC%E5%9B%B3%EF%BC%88%E3%82%AA%E3%83%AB%E3%82%BD%E7%94%BB%E5%83%8F%EF%BC%89#16/36.0989/139.9667)

**Comment by johofukyu** [comment]
frogcat 様
ありがとうございます。
反映させていただきました。
